### ISSUE TITLE
Support no_primitive_wrappers as field level option

### ISSUE THREAD

**Issue by aquamatthias** [scalapb/ScalaPB#361] opened 2017-11-07 14:27 UTC
We switched the rendering of timestamps from `string` to `google.protobuf.Timestamp`.
The created class had a simple string and is now `timestamp: scala.Option[com.google.protobuf.timestamp.Timestamp] = None`

I generally like to handle options and don't want to turn `no_primitive_wrappers` on globally.
Is there a field level option, that gets rid of the option on that very field?

**Comment by thesamet** [comment] 2017-11-07 23:53
Duplicate of #40 which I've just reopened. This came up multiple times, so I think we should do it.

**Closed by thesamet** 2017-11-07 23:53 UTC
