### ISSUE TITLE
Running sbt package with protobuf dependency gives error on windows 10

### ISSUE THREAD

**Issue by ajanaliz** [scalapb/ScalaPB#407] opened 2018-02-19 00:58 UTC
hello, i tried to run my scala code that has protobuf dependancies but the following errors occured:
```
Traceback (most recent call last):
  File "C:\Users\ALIJ~1\AppData\Local\Temp\protocbridge1005986218620043078.py", line 6, in <module>
    s.sendall(content)
TypeError: a bytes-like object is required, not 'str'
--scala_out: protoc-gen-scala: Plugin failed with status code 1.
[trace] Stack trace suppressed: run last compile:protocGenerate for the full output.
[error] (compile:protocGenerate) protoc returned exit code: 1
[error] Total time: 14 s, completed Feb 19, 2018 4:24:09 AM
```

I have 
```"com.trueaccord.scalapb" %% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion % "protobuf",``` 
in my build.sbt

and in my app.proto file i have listed:
```syntax = "proto3";

package com.app;

import "google/protobuf/empty.proto";

message Resource {
    string title = 1;
    string domain = 2;
}

service CrawlerService {
    rpc GetResources (google.protobuf.Empty) returns (stream Resource) {}
}
```

**Comment by thesamet** [comment] 2018-02-19 01:09
Hi @ajanaliz , this is a duplicate of https://github.com/scalapb/ScalaPB/issues/268. The fix is going to come out today (coincidentally I'm working on it right now).  You can find a temporary workaround on that issue.

**Closed by thesamet** 2018-02-19 01:09 UTC

**Comment by ajanaliz** [comment] 2018-02-19 01:11
oh wow.. quite the coincidence. Thanks for the good news

**Comment by thesamet** [comment] 2018-02-19 02:41
As mentioned on #268, this can be resolved by updating sbt-protoc to 0.99.15

**Comment by ajanaliz** [comment] 2018-02-20 12:32
nope, still gave me the following error:

```
Error: Could not find or load main class protocbridge.frontend.BridgeApp
--scala_out: protoc-gen-scala: Plugin failed with status code 1.
[trace] Stack trace suppressed: run last compile:protocGenerate for the full output.
[error] (compile:protocGenerate) protoc returned exit code: 1
[error] Total time: 6 s, completed Feb 20, 2018 4:01:45 PM
```

**Comment by thesamet** [comment] 2018-02-20 17:19
Let's continue the discussion on the main ticket (#268). Can you provide over there a copy of your `build.sbt`?
