### ISSUE TITLE
oneof option for providing whole field mapping.

### ISSUE THREAD

**Issue by mushtaq** [scalapb/ScalaPB#346] opened 2017-09-19 04:09 UTC
Currently typemappers can be provided only for individual item within a oneof field like:

```
oneof items  {
  BankAccount bankAccount = 1 [(scalapb.field).type = "MyCustomType1"];
  CreditAccount creditAccount = 2 [(scalapb.field).type = "MyCustomType2"];  
}
```

It will be also be good to have a option to map the items as a whole, like:

```
oneof items  {
 (scalapb.field).type = "MyBaseType"
  BankAccount bankAccount = 1 [(scalapb.field).type = "MyCustomType1"];
  CreditAccount creditAccount = 2 [(scalapb.field).type = "MyCustomType2"];  
}
```

**Comment by thesamet** [comment] 2017-10-22 15:36
What should the TypeMapper interface look like in this case? I.e. what would be a convenient way for a user to provide a function that converts the generated one of to a custom one and back?

**Comment by mushtaq** [comment] 2017-10-29 14:49
We should assume that MyBaseType is implemented by all oneof mapped types (MyCustomType1, MyCustomType2). We should also allow MyCustomType1/2 annotations right inside the BankAccount/CreditAccount types.

I know this is tricky, but can not think about clearly right now. The workaround in our code used a [typeclass approach](https://github.com/tmtsoftware/csw-prod/blob/master/csw-messages/src/main/scala/csw/messages/params/pb/ItemsFactory.scala)

**Comment by thesamet** [comment] 2017-12-03 23:27
In 0.7.x we are adding a `ValueType` type member to GeneratedOneof that makes it easier to write type classes to deal with oneofs in a more generic way.

When you get a chance can you take a look at https://github.com/scalapb/ScalaPB/commit/b6eab8da7ef1573386331ef8758d750fe693d829 and see if this is solving it for your use case? If not, can you elaborate on your use case.

**Comment by thesamet** [comment] 2017-12-03 23:28
Example usage is here: https://github.com/scalapb/ScalaPB/blob/b6eab8da7ef1573386331ef8758d750fe693d829/e2e/src/test/scala/OneofTypeClasses.scala

**Comment by mushtaq** [comment] 2017-12-12 17:45
This is good.

Thinking more about it, if companion of GeneratedOneof has a concrete
factory method def from(x: Any): Items then that will directly solve my
requirement.

Auto-generated implementation will pattern match on all ValueType
variations and construct appropriate subtypes of Items.

**Comment by thesamet** [comment] 2017-12-12 17:53
The issue is that the same type may appear more than once in a oneof.

**Comment by mushtaq** [comment] 2017-12-13 04:27
Oh, right. I am yet to fully understand PB's way of modelling.

**Comment by thesamet** [comment] 2018-04-17 09:28
I'm closing this issue as it is unclear how to move forward. If there are concrete suggestions or feature requests please don't hesitate to open a new ticket.

**Closed by thesamet** 2018-04-17 09:28 UTC
