### ISSUE TITLE
Restore `Option[T]` handling in generated classes

### ISSUE THREAD

**Issue by zbeckman** [scalapb/ScalaPB#456] opened 2018-06-11 04:48 UTC
According to the ScalaPB docs, we can expect generated classes to use an `Option[T]` for any field that is specified as `optional`:
```
final case class Person(
    name: Option[String] = None,
    age: Option[Int] = None,
    addresses: Seq[Address] = Nil) extends GeneratedMessage {

    def toByteArray: Array[Byte] = { ... }

    // more stuff...
}
```
(Above quoting: https://scalapb.github.io/generated-code.html).

However, when using `proto3` the `optional` keyword is now disallowed:
```
pb.proto:33:14: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
[error] java.lang.RuntimeException: protoc returned exit code: 1
```
Unfortunately, when removing the `optional` specifier (as instructed to do in the above), the generated classes no longer take `Option[T]`, but now expect a simple type:
```
[error] /Users/zbeckman/Projects/Lightbend/NCL/zero-ship-service/ship/src/main/scala/com/ncl/acl/protobuf/ShipProtobufSerializer.scala:34:94: type mismatch;
[error]  found   : Some[String]
[error]  required: String
[error] 	protected implicit def toPbSummary(summary: Summary): SummaryPB = ShipSummaryPB(Some("ABC"), ...)
```
Accordingly it appears that in `proto3` it is no longer possible to represent optional types (in the sense of Scala `Option[T]`).

**Comment by thesamet** [comment] 2018-06-11 06:12
Hi @zbeckman , the wire format in proto2 and proto3 are different. In proto3, an empty string is not serialized, so the parser can't tell between `Some("")` and None. The semantics is that when nothing appears, it is assumed to be an empty string.

You can still get an `Option[T]` generated for you if you use primitive wrappers, see: https://scalapb.github.io/customizations.html#primitive-wrappers

Thanks for pointing out that the documentation is out of date. I updated it, and since this keeps coming every now and then I added an FAQ: https://scalapb.github.io/faq.html#how-do-i-represent-optiont-in-proto3-for-scalar-fields

Hope this helps. I'm closing as things are working as designed. Feel free to reach out over the mailing list, gitter, etc if you have any further question on this.

**Closed by thesamet** 2018-06-11 06:12 UTC
