### ISSUE TITLE
Refer generated class files in sub projects

### ISSUE THREAD

**Issue by sidtandon2014** [scalapb/ScalaPB#752] opened 2020-02-06 11:52 UTC
Hi,

I am able to generate scala files from proto message, and able to execute the flow end to end. This is working fine if there is one main project, but I am unable to refer these generated files from subprojects. How can I do that?

**Comment by thesamet** [comment] 2020-02-06 16:29
duplicate of thesamet/sbt-protoc#137

**Closed by thesamet** 2020-02-06 16:29 UTC
