### ISSUE TITLE
The shaded compiler plugin doesn't work with the newest cross-built sbt plugin

### ISSUE THREAD

**Issue by jvican** [scalapb/ScalaPB#313] opened 2017-07-26 11:19 UTC
Sbt plugin is cross-built for 1.0.0-RC2.
  
I add the following to the Zinc build:
```scala
addSbtPlugin(("ch.epfl.scala" % "sbt-protoc" % "0.99.12-rc4"))
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin-shaded" % "0.6.1"
```
  
The plugin fails with:
```
protoc-jar: executing: [/tmp/protocjar5342621741905762386/bin/protoc.exe, --plugin=protoc-gen-scala=/tmp/protocbridge1208002587562875867, --scala_out=grpc:/data/rw/code/scala/zinc/internal/zinc-persist/target/scala-2.12/src_managed/main, -I/data/rw/code/scala/zinc/internal/zinc-persist/src/main/protobuf, -I/data/rw/code/scala/zinc/internal/zinc-persist/target/protobuf_external, /data/rw/code/scala/zinc/internal/zinc-persist/src/main/protobuf/schema.proto]
java.lang.NoSuchMethodError: com.trueaccord.scalapb.Scalapb.registerAllExtensions(Lscalapb/com/google/protobuf/ExtensionRegistry;)V
	at scalapb.ScalaPbCodeGenerator$.registerExtensions(ScalaPbCodeGenerator.scala:12)
	at protocbridge.frontend.PluginFrontend$.runWithBytes(PluginFrontend.scala:52)
	at protocbridge.frontend.PluginFrontend$.runWithInputStream(PluginFrontend.scala:67)
	at protocbridge.frontend.PosixPluginFrontend$.$anonfun$prepare$1(PosixPluginFrontend.scala:25)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
  
If I try without the `exclude`, I get a similar error:
```scala
protoc-jar: protoc version: 330, detected platform: linux/amd64
protoc-jar: executing: [/tmp/protocjar6501435880370529238/bin/protoc.exe, --plugin=protoc-gen-scala=/tmp/protocbridge8888943732119849368, --scala_out=grpc:/data/rw/code/scala/zinc/internal/zinc-persist/target/scala-2.12/src_managed/main, -I/data/rw/code/scala/zinc/internal/zinc-persist/src/main/protobuf, -I/data/rw/code/scala/zinc/internal/zinc-persist/target/protobuf_external, /data/rw/code/scala/zinc/internal/zinc-persist/src/main/protobuf/schema.proto]
java.lang.AbstractMethodError: Method scalapb/ScalaPbCodeGenerator$.run(Lcom/google/protobuf/compiler/PluginProtos$CodeGeneratorRequest;)Lcom/google/protobuf/compiler/PluginProtos$CodeGeneratorResponse; is abstract
	at scalapb.ScalaPbCodeGenerator$.run(ScalaPbCodeGenerator.scala)
	at protocbridge.frontend.PluginFrontend$.$anonfun$runWithBytes$1(PluginFrontend.scala:56)
	at scala.util.Try$.apply(Try.scala:209)
	at protocbridge.frontend.PluginFrontend$.runWithBytes(PluginFrontend.scala:54)
	at protocbridge.frontend.PluginFrontend$.runWithInputStream(PluginFrontend.scala:67)
	at protocbridge.frontend.PosixPluginFrontend$.$anonfun$prepare$1(PosixPluginFrontend.scala:25)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
  
This must be a problem with the shaded version of the compiler plugin, because removing `shaded` from the compiler plugin artifact makes it work.

Does anyone know what's going on? I've had a look at other tickets reporting similar problems, but this one seems genuine on its own, and the solutions reported before don't work.

**Comment by thesamet** [comment] 2017-09-24 19:03
The problem should be fixed in ScalaPB >= 0.6.4.

**Comment by jvican** [comment] 2017-09-24 20:19
Thank you @thesamet.

**Comment by grollinger** [comment] 2018-01-19 11:20
Hi, we are trying to upgrade to sbt 1.1 and ran into this issue.

Unfortunately, because of our dependencies we have to use scalapb version 0.5.47.

When we upgrade the compiler-plugin to the latest version 0.6.6, the issue described here indeed disappears, but the generated code is no longer compatible with the 0.5.47 runtime.

@thesamet Do you have any suggestions of how we could work around this issue?
Would it be possible/easy to backport the fix to the 0.5.x branch?

**Comment by thesamet** [comment] 2018-01-19 19:16
Reopening this for the backport into 0.5.x.

**Comment by thesamet** [comment] 2018-02-05 04:40
@grollinger - I published version 0.5.48 that supposed to be make ScalaPB 0.5.x compatible with SBT 1.0.x. Due to binary incompatibilities that were introduced as a result of this change, you would have to also upgrade `sbt-protoc` to at least 0.99.12 (0.99.14 is the most recent version). Can you report if this resolves the issue for you?

**Comment by grollinger** [comment] 2018-02-05 20:40
When using the new version, I'm still getting 

```
java.lang.AbstractMethodError: Method scalapb/ScalaPbCodeGenerator$.run([B)[B is abstract              
        at scalapb.ScalaPbCodeGenerator$.run(ScalaPbCodeGenerator.scala)                               
        at protocbridge.frontend.PluginFrontend$.$anonfun$runWithBytes$1(PluginFrontend.scala:50)      
        at scala.util.Try$.apply(Try.scala:209)   
...
```
And the compile hangs.

In the meantime, we came up with a workaround, though.
We now have the following in our `plugins.sbt`:

```scala
val scalaPbVersion = "0.5.47"
dependencyOverrides ++= Seq(
  "com.trueaccord.scalapb" %% "protoc-bridge" % "0.2.5", //warning: 0.3+ uses a different interface
  "com.trueaccord.scalapb" %% "scalapb-runtime" % scalaPbVersion
)
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % scalaPbVersion
```
With that, we are able to compile successfully.

Thank you for your support @thesamet.

**Comment by thesamet** [comment] 2018-02-05 20:45
I am curious if you are you getting this error when the compilerplugin is set to 0.5.48, not just scaslapb-runtime?

**Comment by grollinger** [comment] 2018-02-05 21:09
This fails:
```scala
val scalaPbVersion = "0.5.48"
dependencyOverrides ++= Seq(
//   "com.trueaccord.scalapb" %% "protoc-bridge" % "0.2.5", //warning: 0.3+ uses a different interface
)
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % scalaPbVersion
```

while this succeeds:
```scala
val scalaPbVersion = "0.5.48"
dependencyOverrides ++= Seq(
  "com.trueaccord.scalapb" %% "protoc-bridge" % "0.2.5", //warning: 0.3+ uses a different interface
)
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % scalaPbVersion
```

So the decisive factor is the `protoc-bridge` override.

**Comment by thesamet** [comment] 2018-02-05 21:52
Strange, my test yesterday didn't reproduce this. Is the workaround that you found good enough until you are able to catch up on a more recent ScalaPB version? If not, would you be able to send a minimal example?

**Comment by grollinger** [comment] 2018-02-06 13:25
Yes, it's good enough for now. 

Many thanks for your efforts 😃

**Closed** 2018-02-06 19:06 UTC
