### ISSUE TITLE
Merge errors in sbt assembly when upgrading to 0.6.6

### ISSUE THREAD

**Issue by pradyuman** [scalapb/ScalaPB#371] opened 2017-11-24 17:56 UTC
I'm upgrading from 0.6.0 -> 0.6.6 right now and I'm getting the following errors:
<img width="1272" alt="screen shot 2017-11-24 at 11 49 46 am" src="https://user-images.githubusercontent.com/9904569/33220489-5ea53b70-d10e-11e7-98b4-223b609401a0.png">

I've upgraded sbt-protoc from 0.99.8 to 0.99.12 as well. I didn't get these errors earlier; is there something I'm doing incorrectly? Or should I just resolve this using MergeStrategy.first and not worry about any potential errors?

**Comment by thesamet** [comment] 2017-11-24 19:45
Can you provide an example on how to reproduce this issue? Looks like you
are getting two versions of the same classes.

**Comment by pradyuman** [comment] 2017-11-25 00:12
build.sbt module:
```
lazy val proto = (project in file("modules/proto"))
  .settings(
    commonSettings,
    name := "common-proto",

    libraryDependencies ++= Seq(
      // Proto stuff
      "com.trueaccord.scalapb" %% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion % "protobuf",
      "com.trueaccord.scalapb" %% "scalapb-runtime-grpc" % com.trueaccord.scalapb.compiler.Version.scalapbVersion,
      "io.grpc" % "grpc-netty" % "1.7.0"
    ),

    PB.protoSources in Compile := Seq(
      file("modules/proto/src/main/proto")
    ),

    PB.targets in Compile := Seq(
      scalapb.gen(
        flatPackage = true,
        grpc = true
      ) -> (sourceManaged in Compile).value
    ),

    // Include managed sources (ie protobuf) in sources jar
    mappings in (Compile, packageSrc) ++= { // publish generated sources
      val srcs = (managedSources in Compile).value
      val sdirs = (managedSourceDirectories in Compile).value
      val base = baseDirectory.value
      (((srcs --- sdirs --- base) pair (relativeTo(sdirs) | relativeTo(base) | flat)) toSeq)
    }
  )
```

scalapb.sbt:
```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.12")
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % "0.6.6"
```

**Comment by thesamet** [comment] 2017-11-25 15:33
It would be great if you can provide a minimal working example - here `commonSettings` is undefined, and the sbt assembly is not mentioned. Would be best to set up a git repository or send over a zip file. Alternatively, can you find what are the two jars providing the conflicting files and  how they get into your dependencies?

**Comment by thesamet** [comment] 2018-01-14 21:14
Based on the screenshot, I think that there is a copy of scalapb.proto in the projects directory so we get two copies of this file.

Since there was no update here for a while, I'll close the issue. Feel free to open a new issue or add a comment here if the issue isn't resolved.

**Closed by thesamet** 2018-01-14 21:14 UTC
