### ISSUE TITLE
Scala 3 on Gradle: This TASTy file was produced by a more recent, forwards incompatible release

### ISSUE THREAD

**Issue by elbaulp** [scalapb/ScalaPB#1152] opened 2021-05-20 10:00 UTC
Hello, I'm trying to use scalapb for building protos for scala3, but I'm facing this problem:

```
This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.0.0.
Note that your tooling is currently using an unstable TASTy version.)
[Error] : error while loading PRepeated, class file '****files-2.1/com.thesamet.scalapb/scalapb-runtime_3/0.11.3/86b2c93524fec05ac8e5bd5553729f25c051a115/scalapb-runtime_3-0.11.3.jar(scalapb/descriptors/PRepeated.class)' is broken
(class scala.tools.tasty.UnpickleException/TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 0 [unstable release: 1]}
 found   : {majorVersion: 28, minorVersion: 0}
```

But I'm confuse, since the expected and founded versions are matching.

I'm using this version of scala:

```
    implementation("org.scala-lang:scala3-library_3:3.0.0")
```

Any idea what may be happening?

**Comment by thesamet** [comment] 2021-05-20 14:28
@elbaulp Can you provide a minimal project (ideally on github) that demonstrates this problem?

**Comment by thesamet** [comment] 2021-05-20 14:29
Given the line:

> expected: {majorVersion: 28, minorVersion: 0 [unstable release: 1]}

Is it possible that you are not on the final 3.0.0?

**Comment by elbaulp** [comment] 2021-05-25 07:41
> Given the line:
> 
> > expected: {majorVersion: 28, minorVersion: 0 [unstable release: 1]}
> 
> Is it possible that you are not on the final 3.0.0?

Yes, I'm using 3.0.0. I'll try to write a minimal project at some point this week.

Thanks for answering

**Comment by elbaulp** [comment] 2021-05-27 08:24
BTW, I'm using gradle instead of sbt. Is that a problem?

**Comment by thesamet** [comment] 2021-05-27 14:02
We would like it to work, but it is very likely you are the first one to be on the Gradle & ScalaPB & Scala3 intersection. Once I have your minimal project locally I'll give it a try.

**Comment by elbaulp** [comment] 2021-05-28 11:54
@thesamet Cool, sorry I did not have time this week. Hopefully next week (I'm only working on this project once a week)

**Comment by elbaulp** [comment] 2021-06-03 10:01
@thesamet sorry for taking so long, here it is: 

https://github.com/elbaulp/scalapb-scala3

Just run `make build` and you should get the TASTy error

**Comment by ahjohannessen** [comment] 2021-06-03 10:15
Try to use Scala 3.0.1-RC1 and sbt 1.5.3

**Comment by elbaulp** [comment] 2021-06-03 10:38
> Try to use Scala 3.0.1-RC1 and sbt 1.5.3

Unfortunately I can not use sbt, I need gradle, because I'm automatically generating hundreds of project on the fly to be compiled, and [sbt does not allow me](https://stackoverflow.com/questions/66367587/dynamically-create-subprojects-in-scala-sbt) to dynamically create submodules

**Comment by thesamet** [comment] 2021-06-03 16:35
@elbaulp , thanks for setting up the test project. Based on it and the pre-existing [https://github.com/scalapb/gradle-demo](gradle-demo) repo, I created a [Scala 3 branch](https://github.com/scalapb/gradle-demo/tree/scala3) which we can continue to collaborate on this issue. I would like to stick with the approach there which does not involve checking in binaries such as `protoc` and `protoc-gen-scalapb`. 

Through this, I was able to reproduce the error you reported. Based on some Google search, I have found out that there is no official support for Scala 3 in gradle yet and people are using all sort of temporary hacks to get the compiler to be correctly invoked. See [this for example](https://github.com/michelou/dotty-examples/blob/master/myexamples/common.gradle).

At this point, I am not sure that in your repo nor the one I provided, the Scala 3 compiler is invoked correctly, and therefore I'm not sure if this is a ScalaPB-specific issue at all.

**Comment by elbaulp** [comment] 2021-06-04 10:48
Yeah, I have the feeling that the generated Scala code is not Scala 3 even though in Gradle we're specifying `3.0.0`.

How should we proceed? Should we wait until Gradle officially supports Scala 3? Maybe when they do the error is gone and there is no need to invest time on this.

On the contrary, we can try to make it work on the Scala 3 branch you mentioned. 

I'm happy to help in whatever I can

**Comment by thesamet** [comment] 2021-06-04 15:20
> Yeah, I have the feeling that the generated Scala code is not Scala 3 even though in Gradle we're specifying 3.0.0.

The code generated by ScalaPB compiles with both Scala 2 and Scala 3 - there's no Scala 3 specific code generated. I believe that the issue is that the Scala 3 compiler is not invoked in the build, or not invoked correctly. I think that the issue will resolve on its own once Scala 3 is supported on Gradle.

**Comment by thesamet** [comment] 2021-06-12 23:13
Blocked on https://github.com/gradle/gradle/issues/16527

**Comment by thesamet** [comment] 2022-05-08 15:35
The underlying gradle bug has been fixed. No action needed on ScalaPB side so closing.

**Closed by thesamet** 2022-05-08 15:35 UTC
Labels: blocked
