### ISSUE TITLE
ValueType in proto causes name conflict

### ISSUE THREAD

**Issue by crispywalrus** [scalapb/ScalaPB#335] opened 2017-09-07 20:38 UTC
see https://gist.github.com/crispywalrus/a3d9610f15f97967cb4c1b4495df30c6 for a simple repo case with output.

The googleapis code produces enum's with name `ValueType` which conflicts with scalapb's own `ValueType`

**Comment by thesamet** [comment] 2017-09-23 04:39
Duplicate of #348

**Closed by thesamet** 2017-09-23 04:39 UTC
