### ISSUE TITLE
Match may not be exhaustive error when compiling with TLS 2.12.1

### ISSUE THREAD

**Issue by notxcain** [scalapb/ScalaPB#262] opened 2017-03-30 12:31 UTC
I have this message
```protobuf
message Foo {
    required Bar bar = 1;
}
enum Bar {
    Baz = 1;
}
```
and `build.sbt` like this
```sbt
scalaOrganization := "org.typelevel"
scalaVersion := "2.12.1"
scalacOptions ++= Seq("-Xfatal-warnings", "-Xlint")
```
I'm getting `match may not be exhaustive. It would fail on the following input: (x: Int forSome x not in 1)` inside `Foo.enumCompanionForField` method on the line with pattern matching on ` __field.getNumber`.

Could it be made total? 
Maybe by throwing some kind of exception or maybe returning an `Option[GeneratedEnumCompanion[_]]` ?

**Comment by thesamet** [comment] 2017-03-31 06:32
I am not able to reproduce this problem on 0.5.x and 0.6.x using the SBT versions you provided. Which version of ScalaPB are you using? Can you provide a complete minimal example I can clone and test?

**Comment by notxcain** [comment] 2017-03-31 07:24
@thesamet My bad! It turned out that `-Xlint` compiler flag had to be added. Anyway here's a repro https://github.com/notxcain/scalapb-repro.

**Comment by notxcain** [comment] 2017-03-31 07:31
As @sellout [suggested](https://gitter.im/typelevel/scala?at=58dd0a0e7ea420cc421ed0a4) on Gitter, it is possible to add `@unchecked` if exhaustivity could not be proved statically.

**Comment by sellout** [comment] 2017-03-31 15:20
Yeah, this has come up a few times since Typelevel Scala 2.12.1 was released with better exhaustivity checking.

There is a new `-Xlint` subflag, `strict-unsealed-patmat`, which warns on inexhaustive pattern matches of unsealed types. My guess is that the code generated by ScalaPB covers all possible cases, but scalac can’t tell. I think here, rather than returning `Option`, generating `(foo: @unchecked) match { ... }` is the better approach. Or, maybe have a catchall that throws something more descriptive than the `MatchError` that would otherwise be raised.

**Closed** 2017-04-01 03:20 UTC

**Comment by notxcain** [comment] 2017-04-01 05:22
@thesamet awesome, thanks!
