### ISSUE TITLE
ScalaPBC: support user-configurable protoc locations?

### ISSUE THREAD

**Issue by copumpkin** [scalapb/ScalaPB#362] opened 2017-11-10 20:06 UTC
I'm on a platform where the usual jar full of `protoc` binaries doesn't work. I do have a `protoc` binary of my own that does work, but I don't know how to convince ScalaPB to use it. Is there a flag for that, or if not, can there be one?

**Comment by thesamet** [comment] 2017-11-12 03:54
This is documented at the bottom of https://github.com/thesamet/sbt-protoc:

```
// Use a locally provided protoc:
PB.runProtoc := (args => Process("/path/to/protoc", args)!)
```

**Comment by nmost** [comment] 2017-11-15 19:23
@thesamet I'm using pants and don't see a similar configuration option in their java_protobuf_library. Looking at https://github.com/scalapb/ScalaPB/blob/master/scalapbc/src/main/scala/com/trueaccord/scalapb/ScalaPBC.scala around line 30 it seems clear that there's no good way to specify a protoc location for scalapb itself. Falling back to sbt-protoc isn't a great option when you're on another build system :)

**Comment by thesamet** [comment] 2017-11-15 19:35
Ok. I assumed that you're using SBT. Yes, it's currently impossible to specify a custom protoc with ScalaPBC but should be, so I reopened this issue.

Out of curiosity, you wrote that you are on a platform that isn't supported by protoc-jar. Which one it is?

**Comment by copumpkin** [comment] 2017-11-15 20:24
NixOS, which has glibc (and thus the standard ELF interpreter) in a non-FHS location. There are similar known issues on Alpine (musl-based) and (I'd bet) gobolinux.

Thanks for reopening! I think if `scalapbc`'s main function could just take an optional argument for the protoc location (which we could then invoke from the pants plugin) that would fix all our issues.

**Comment by nmost** [comment] 2017-11-20 20:43
I believe this can be closed after https://github.com/scalapb/ScalaPB/pull/367

**Comment by thesamet** [comment] 2017-11-20 22:53
We will also need to pass the new flag from the pants plugin (see https://github.com/scalapb/scalapb-pants/blob/master/src/python/trueaccord/pants/scalapb/tasks/scalapb_gen.py). @copumpkin will you be able to help with that?

**Comment by nmost** [comment] 2017-11-20 22:55
@thesamet I have a version of that locally (currently not working). I'll submit upstream when it's working as intended for me

**Comment by thesamet** [comment] 2018-05-26 17:43
Closing for now as the original issue has been addressed in #367, if anyone ever needs custom protoc support in pants please file a separate ticket.

**Closed by thesamet** 2018-05-26 17:43 UTC

**Comment by omrihq** [comment] 2020-02-26 23:47
@nmost Reopening this a few years later.. but did you have any luck getting this working with Pants? I'm revisiting this project now and attempting to get it going with pants

**Comment by thesamet** [comment] 2020-02-26 23:54
ScalaPBC still doesn't have an option for a specifying custom protoc. I'll be happy to accept a PR that adds this. Alternatively, you can try to download `protoc-gen-scala` for your platform (unix or windowss) and use it directly as a protoc plugin.

**Comment by nmost** [comment] 2020-02-26 23:55
> @nmost Reopening this a few years later.. but did you have any luck getting this working with Pants? I'm revisiting this project now and attempting to get it going with pants

I did, with a custom pants plugin. Eventually we abandoned this effort altogether and went back to Java implementations of protobuf (and just used the builder pattern)
