### ISSUE TITLE
Usage of deprecated javaGenerateEqualsAndHash

### ISSUE THREAD

**Issue by leozilla** [scalapb/ScalaPB#550] opened 2019-03-01 16:06 UTC
When I compile my protos I get a lot of the following warnings.
```
/target/scala-2.12/src_managed/main/com/google/protobuf/descriptor/FileOptions.scala:306:46: value javaGenerateEqualsAndHash in class FileOptions is deprecated: Marked as deprecated in proto file
[warn]       var __javaGenerateEqualsAndHash = this.javaGenerateEqualsAndHash
```
Is this a known "issue"? (cos I havn't found an open/closed issue for it)

**Comment by thesamet** [comment] 2019-03-02 17:22
It looks like you are generating Scala for `descriptor.proto` - this is shipped with ScalaPB's runtime, so there is no need to compile it yourself. When you compile a proto file that has deprecated fields you would get deprecation warnings because there is generate code that references those fields.

One workaround would be to compile some of the protos in a separate compilation step (different sbt subproject for example), so you could ignore these errors if they appear in a certain part of your code.

It would be nice if ScalaPB could somehow suppress the deprecation warnings that result from its own usage of the deprecated methods, but this is currently not supported. See https://github.com/scala/bug/issues/7934

Since things currently work as designed for ScalaPB I am closing this issue, but feel free to discuss further over the various channels.

**Closed by thesamet** 2019-03-02 17:22 UTC

**Comment by leozilla** [comment] 2019-03-03 18:45
I am not really sure whats going on and how I should fix this.

It happens once I add `"com.thesamet.scalapb" %% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion % "protobuf"` to my `libraryDependencies` which I need for the google protos like `timestamp.proto` and when I also use the `AkkaGrpcPlugin`.

When I compile just my single proto file which includes the google timestamp proto without the `AkkaGrpcPlugin` but with the `scalapb-runtime` dependency then it works.

**Comment by plaflamme** [comment] 2023-01-27 20:53
@thesamet suppressing warnings in narrow scopes is now [well supported](https://www.scala-lang.org/2021/01/12/configuring-and-suppressing-warnings.html) using the `@nowarn` annotation. e.g.: `@scala.annotation.nowarn("cat=deprecation")` on methods, fields, etc. It'd be nice if this could be enabled by default or optionally or whatever. It requires scala >= 2.12.13 or >= 2.13.2 so it seems pretty safe to turn on by default.

**Comment by thesamet** [comment] 2023-01-27 20:59
Yes. PR that emits `@nowarn` for generated code that uses deprecated fields will be accepted.
